# Book settings
title: "Brain State Predictions"
author: Chirag Limbachia
copyright: "2020"
logo: "logo.png"
exclude_patterns            : ["tensorflow/*","0*","99*",
                                "training_data_description",
                                "notebooks/00-ROI316_withShiftedSegments/*",
                                "notebooks/00-ROI316_last_segment/99*",
				"notebooks/03-rAI/02*"]

execute:
  exclude_patterns: ["tensorflow/lib/python3.6/site-packages/jupyter_book/book_template/notebooks","tensorflow/lib/python3.6/site-packages/matplotlib/backends/web_backend/nbagg_uat","tensorflow/lib/python3.6/site-packages/nbclient/tests/files/Autokill","0*","99*","notebooks/*"]
latex:
  latex_documents:
    targetname: book.tex

###########################################################################
# To render images 
parse:
  myst_extended_syntax: true
###########################################################################
# HTML-specific settings
html:
  home_page_in_navbar: false
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: true

##########################################################################
# Launch button settings
repository:
  url: https://github.com/limbachia/brain-state-predictions
latex:
  latex_engine: "xelatex"
  latex_documents:
    targetname: book.tex
